package by.haardd.cclog.exception.types;

public enum ErrorCode {

    RESOURCE_NOT_FOUND, RESOURCE_NOT_CREATED, RESOURCE_NOT_UPDATED, RESOURCE_NOT_DELETED,
    TOKEN_NOT_FOUND, TOKEN_EXPIRED,
    AUTH_NOT_UNAUTHORIZED, AUTH_ACCESS_DENIED, AUTH_SIGNUP_CODE_NOT_FOUND, AUTH_SIGNUP_USER_ALREADY_EXIST

}
